const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.video,
		C3.Behaviors.bound,
		C3.Plugins.iframe,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Plugins.Particles,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Camera3D,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsSuspended,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mouse.Acts.ReleasePointerLock,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.iframe.Acts.NavigateURL,
		C3.Plugins.iframe.Acts.SetVisible,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Diary1: 0},
	{Diary2: 0},
	{DiaryBG: 0},
	{Diary3: 0},
	{Diary4: 0},
	{diary_intro: 0},
	{Xdiary: 0},
	{diary_lessonX: 0},
	{finish: 0},
	{finish2: 0},
	{finish3: 0},
	{finish4: 0},
	{startb: 0},
	{startbg: 0},
	{Xstart: 0},
	{start_intro: 0},
	{SKIP: 0},
	{"1_1talkBG": 0},
	{"1_1talk1": 0},
	{"1_1talk2": 0},
	{X1_1: 0},
	{talk: 0},
	{talk2: 0},
	{Chihuahua: 0},
	{Chihuahua_information: 0},
	{Pomeranian: 0},
	{Pomeranian_information: 0},
	{iknow_1_2_2: 0},
	{Pug: 0},
	{Pug_information: 0},
	{dachshund: 0},
	{dachshund_information: 0},
	{iknow_1_2_3: 0},
	{iknow_1_2_4: 0},
	{corgi: 0},
	{corgi_information: 0},
	{borderCollie: 0},
	{borderCollie_information: 0},
	{iknow_1_2_5: 0},
	{goldenRetriever: 0},
	{goldenRetriever_information: 0},
	{Labrador: 0},
	{Labrador_information: 0},
	{iknow_1_2_6: 0},
	{molosser: 0},
	{molosser_informationpng: 0},
	{CaucasianSheepdog: 0},
	{CaucasianSheepdog_informationpng: 0},
	{"1_2_firstpage_bigSquare": 0},
	{"1_2_firstpage_giantSquare": 0},
	{"1_2_firstpage_mediumSquare": 0},
	{"1_2_firstpage_miniSquare": 0},
	{"1_2_firstpage_smallSquare": 0},
	{"1_2_fistpageBackground": 0},
	{first_teach: 0},
	{"1_2lesson": 0},
	{cross_teach: 0},
	{cross_lesson: 0},
	{cross_tip: 0},
	{"1_1_X": 0},
	{"1_1background": 0},
	{"1_1bigSquare": 0},
	{correct: 0},
	{DragDrop: 0},
	{"1_1borderCollieSquare": 0},
	{"1_1CaucasianShepherdDog": 0},
	{"1_1ChihuahuaSquare": 0},
	{"1_1corgiSquare": 0},
	{"1_1dachshundSquare": 0},
	{"1_1giantSquare": 0},
	{"1_1goldenRetriever": 0},
	{"1_1intro": 0},
	{"1_1LabradorSquare": 0},
	{"1_1mediumSquare": 0},
	{"1_1miniSquare": 0},
	{"1_1PomeranianSquare": 0},
	{"1_1PugSquare": 0},
	{"1_1smallSquare": 0},
	{"1_1teach": 0},
	{"1_1tibetanMastiff": 0},
	{"1_2_2background": 0},
	{"1_2_2intro": 0},
	{"1_2_2teach": 0},
	{Sprite: 0},
	{text_big: 0},
	{text_big2: 0},
	{text_medium: 0},
	{text_mini: 0},
	{text_small: 0},
	{eatBG: 0},
	{eat_hawaii_bean: 0},
	{eat_chocolote: 0},
	{eat_apple: 0},
	{eat_pitaya: 0},
	{eat_onion: 0},
	{eat_grape: 0},
	{eat_blueberry: 0},
	{eat_watermelon: 0},
	{eat_avocado: 0},
	{eat_chicken_bone: 0},
	{EAT_HAPPYDaiFront: 0},
	{EAT_NO1: 0},
	{EAT_NO3: 0},
	{EAT_NO2: 0},
	{EAT_TASK: 0},
	{EATLIST2: 0},
	{EATiknow: 0},
	{EATintro: 0},
	{talk3: 0},
	{talk4: 0},
	{map_station1_1: 0},
	{map_station1_2: 0},
	{map_station1_3: 0},
	{map_station1_4: 0},
	{map_station1_5: 0},
	{map_station1_6: 0},
	{map_1_1: 0},
	{map_1_2: 0},
	{map_1_3: 0},
	{map_1_4: 0},
	{map_1_5: 0},
	{map_1_6: 0},
	{Xmap2: 0},
	{U1Grass: 0},
	{map_intro: 0},
	{openVideo: 0},
	{map_2_1: 0},
	{map_2_2: 0},
	{map_2_3: 0},
	{map_2_4: 0},
	{"3map": 0},
	{map_3_1: 0},
	{map_3_2: 0},
	{map_3_3: 0},
	{map_3_4: 0},
	{map_3_5: 0},
	{ch4_map: 0},
	{map_: 0},
	{list_logo: 0},
	{list_intro: 0},
	{list_light: 0},
	{list_lesson: 0},
	{list_map: 0},
	{bg: 0},
	{test_1_: 0},
	{"1_3_1A": 0},
	{"1_3_1B": 0},
	{"1_3_1C": 0},
	{"1_3_1D": 0},
	{test_1_2: 0},
	{"1_3_2A": 0},
	{"1_3_2B": 0},
	{"1_3_2C": 0},
	{"1_3_2D": 0},
	{test_1_3: 0},
	{"1_3_3A": 0},
	{"1_3_3B": 0},
	{test_1_4: 0},
	{"1_3_4A": 0},
	{"1_3_4B": 0},
	{"1_3_4C": 0},
	{"1_3_4D": 0},
	{test_1_5: 0},
	{test_1_final: 0},
	{test_1_final_: 0},
	{nextto2: 0},
	{test_1_teach: 0},
	{ans_1_1: 0},
	{ans_1_2: 0},
	{ans_1_3: 0},
	{ans_1_4: 0},
	{ans_1_5: 0},
	{ans_1_1_chose: 0},
	{ans_1_2_chose: 0},
	{ans_1_3_chose: 0},
	{ans_1_4_chose: 0},
	{test_1_next: 0},
	{test_1_final2: 0},
	{next_to_1_2: 0},
	{NEXTTOSPEAK: 0},
	{DaiFront: 0},
	{BG2: 0},
	{next1_2_1: 0},
	{next_level1_3: 0},
	{next_level2_2: 0},
	{BG2_2next: 0},
	{BG1_1next: 0},
	{next_level2_3: 0},
	{next_level2_4: 0},
	{"2_3_1_talk": 0},
	{"2_3_1BG": 0},
	{"2_3_1Grass": 0},
	{"2_3_1Hot": 0},
	{"2_3_1Noise": 0},
	{"2_3_1Walk": 0},
	{"2_3_1_teach": 0},
	{"2_3_2BG": 0},
	{"2_3_ans1": 0},
	{"2_3_r": 0},
	{"2_3_l": 0},
	{"2_3_2_iknow": 0},
	{"2_3_2_teach": 0},
	{"2_3_2_hand": 0},
	{"2_3_2cross": 0},
	{"2_3_2_back": 0},
	{"2_3_2_hand_infor": 0},
	{"2_3_2_mask": 0},
	{Walk_talk: 0},
	{Law: 0},
	{"2_3_2_next": 0},
	{"2_3_2_Hand_move": 0},
	{law_infor: 0},
	{"2_2bg": 0},
	{"2_2bag": 0},
	{"2_2book": 0},
	{"2_2anthelmintics": 0},
	{"2_2doll": 0},
	{"2_2cleaningSupplies": 0},
	{"2_2scooper": 0},
	{"2_2HarnessLesh": 0},
	{"2_2tableware": 0},
	{"2_2water": 0},
	{"2_2lesson": 0},
	{"2_2iknow": 0},
	{"2_2c1": 0},
	{"2_2c2": 0},
	{"2_2c3": 0},
	{"2_2c4": 0},
	{"2_2c5": 0},
	{"2_2X": 0},
	{"2_2X2": 0},
	{"2_2goal": 0},
	{"2_2teach": 0},
	{"2_2talk2": 0},
	{"2_2talk1": 0},
	{"22talk3png": 0},
	{"2_2talkbg": 0},
	{living: 0},
	{airc: 0},
	{ashbin: 0},
	{fence: 0},
	{fnw: 0},
	{AIR: 0},
	{carpet: 0},
	{chest: 0},
	{CHEST2: 0},
	{FENCE2: 0},
	{FOOD: 0},
	{GROUND: 0},
	{house: 0},
	{HOUSE2: 0},
	{TRASH: 0},
	{Xa: 0},
	{XCHEST: 0},
	{Xg: 0},
	{Xr: 0},
	{Xfw: 0},
	{Xh: 0},
	{Xf: 0},
	{no1: 0},
	{no2: 0},
	{"2_1intro": 0},
	{robot2: 0},
	{robottxt2: 0},
	{robotend: 0},
	{Xrobot: 0},
	{"21ani": 0},
	{"21aniskip": 0},
	{"2ov": 0},
	{"2_1OpenVidoe": 0},
	{LIST: 0},
	{ROBOT: 0},
	{ans_2_1A: 0},
	{ans_2_1B: 0},
	{test_2_1: 0},
	{ans_2_1: 0},
	{ans_2_1_chose: 0},
	{ans_2_2A: 0},
	{ans_2_2B: 0},
	{ans_2_2C: 0},
	{ans_2_2D: 0},
	{test_2_2: 0},
	{ans_2_2: 0},
	{ans_2_2_chose: 0},
	{ans_2_3A: 0},
	{ans_2_3B: 0},
	{ans_2_3C: 0},
	{ans_2_3D: 0},
	{test_2_3: 0},
	{ans_2_3: 0},
	{ans_2_3_chose: 0},
	{test_2_4: 0},
	{ans_2_4A: 0},
	{ans_2_4C: 0},
	{ans_2_4B: 0},
	{ans_2_4D: 0},
	{ans_2_4: 0},
	{ans_2_4_chose: 0},
	{ans_2_5A: 0},
	{ans_2_5B: 0},
	{test_2_5: 0},
	{ans_2_5: 0},
	{ans_2_5_chose: 0},
	{test_2_teach: 0},
	{test_2_next: 0},
	{test_2_final: 0},
	{test_2_score: 0},
	{test_2_final_2: 0},
	{nextto3: 0},
	{test_3_final: 0},
	{ch1next: 0},
	{BoundToLayout: 0},
	{stomach_03: 0},
	{knee_03: 0},
	{knee_01: 0},
	{stomach_02: 0},
	{knee_02: 0},
	{stomach_01: 0},
	{"3_2_game_bg": 0},
	{stomach_gif1: 0},
	{knee_gif_1: 0},
	{stomach_gif2: 0},
	{stomach_gif3: 0},
	{knee_gif_2: 0},
	{knee_gif_3: 0},
	{"3_2_game_squareS": 0},
	{"3_2_game_squareK": 0},
	{"3_2_game_teach": 0},
	{"3_2_game_next": 0},
	{"3_2_game_next_arrow": 0},
	{"3_2bg": 0},
	{Ok: 0},
	{teach: 0},
	{iframe: 0},
	{ipad: 0},
	{Look_Continue: 0},
	{Berner: 0},
	{Physics: 0},
	{BernerPink: 0},
	{CaucasianBlue: 0},
	{CaucasianSheepdog2: 0},
	{GreatDane: 0},
	{GreatGreen: 0},
	{molosser2: 0},
	{molosserYellow: 0},
	{Saint: 0},
	{SaintOrange: 0},
	{Solid: 0},
	{"8Direction": 0},
	{DestroyOutsideLayout: 0},
	{ShortPUR: 0},
	{TaiwanMountain_: 0},
	{TaiwanPurple: 0},
	{Ball: 0},
	{BGG: 0},
	{C: 0},
	{Cursor: 0},
	{DistanceRuler: 0},
	{GRASS: 0},
	{NEXT: 0},
	{RestartButton: 0},
	{S: 0},
	{S2: 0},
	{SaintOrange2: 0},
	{SaintOrange3: 0},
	{SB: 0},
	{SDOG: 0},
	{Trail: 0},
	{Bg3: 0},
	{CatapultBlock: 0},
	{Sprite8: 0},
	{DOGS: 0},
	{BD: 0},
	{P1: 0},
	{P2: 0},
	{PBC: 0},
	{PD: 0},
	{PDOG3: 0},
	{PPD: 0},
	{PS1: 0},
	{PS2: 0},
	{Y1: 0},
	{Y2: 0},
	{YC: 0},
	{YD: 0},
	{YD2: 0},
	{YDOG2: 0},
	{YS1: 0},
	{YS2: 0},
	{YY: 0},
	{END: 0},
	{INTRO: 0},
	{X: 0},
	{doghand: 0},
	{"3_4_game_bg": 0},
	{circle_L1: 0},
	{circle_L2: 0},
	{circle_L3: 0},
	{circle_R1: 0},
	{circle_R2: 0},
	{circle_R3: 0},
	{"3_4_eggB": 0},
	{"3_4_eggP": 0},
	{"3_4_game_teach": 0},
	{"3_4_Elf": 0},
	{"3_4_photo": 0},
	{"3_4_tip": 0},
	{"3_4_light": 0},
	{iframe2: 0},
	{"3_4ok": 0},
	{"3_4teach": 0},
	{"3ani": 0},
	{"3_3bg": 0},
	{old_dai: 0},
	{"3_3BAR": 0},
	{"3_3hand": 0},
	{"3_3brush": 0},
	{"3_3eat": 0},
	{"3_3health": 0},
	{"3_3sport": 0},
	{"3_3i": 0},
	{"3_3clean": 0},
	{"3_3_0mouth": 0},
	{"3_3_0brain": 0},
	{"3_3_0drain": 0},
	{"3_3_0eyes": 0},
	{"3_3_0hair": 0},
	{cir_brain: 0},
	{cir_drain: 0},
	{cir_eyes: 0},
	{cir_hair: 0},
	{cir_hearing: 0},
	{cir_mouth: 0},
	{cir_power: 0},
	{"3_3_0hearing": 0},
	{"3_3_0power": 0},
	{"3_30bar": 0},
	{"3_3teach1": 0},
	{NEXT2: 0},
	{"3_3intro2": 0},
	{"3_3END": 0},
	{outtro: 0},
	{"3_3teach2": 0},
	{cursor2: 0},
	{cursor3: 0},
	{test_3_1: 0},
	{ans_3_1A: 0},
	{ans_3_1B: 0},
	{ans_3_1C: 0},
	{ans_3_1D: 0},
	{ans_3_1: 0},
	{ans_3_1_choose: 0},
	{ans_3_2A: 0},
	{ans_3_2B: 0},
	{ans_3_2C: 0},
	{ans_3_2D: 0},
	{test_3_2: 0},
	{ans_3_2: 0},
	{ans_3_2_choose: 0},
	{test_3_3: 0},
	{ans_3_3: 0},
	{ans_3_3_choose: 0},
	{ans_3_3A: 0},
	{ans_3_3C: 0},
	{ans_3_3D: 0},
	{ans_3_3B: 0},
	{ans_3_4: 0},
	{ans_3_4_choose: 0},
	{ans_3_4A: 0},
	{ans_3_4B: 0},
	{ans_3_4C: 0},
	{ans_3_4D: 0},
	{test_3_4: 0},
	{ans_3_5: 0},
	{ans_3_5_choose: 0},
	{ans_3_5A: 0},
	{ans_3_5B: 0},
	{test_3_5: 0},
	{test_3_next: 0},
	{ch3_s1_1: 0},
	{ch3_s2: 0},
	{ch3_s3_1: 0},
	{ch3_s0_1: 0},
	{ch3_s4_1: 0},
	{go3_3: 0},
	{ch3_end: 0},
	{ready_go_4: 0},
	{ch3_s0_2: 0},
	{ch3_s0_3: 0},
	{ch3_s1_2: 0},
	{ch3_s1_3: 0},
	{ch3_s1_4: 0},
	{ch3_s3_2: 0},
	{ch3_s3_3: 0},
	{ch3_s3_4: 0},
	{ch3_s3_7: 0},
	{ch3_s3_5: 0},
	{ch3_s3_6: 0},
	{ch3_s4_2: 0},
	{ch3_end2: 0},
	{bg4: 0},
	{"4_2_w4": 0},
	{QR2: 0},
	{"4_2w1": 0},
	{"4_2w2": 0},
	{k: 0},
	{"4_2w3": 0},
	{ans_4_1A: 0},
	{ans_4_1B: 0},
	{ans_4_1C: 0},
	{ans_4_1D: 0},
	{test_4_1: 0},
	{ans_4_2A: 0},
	{ans_4_2B: 0},
	{ans_4_2C: 0},
	{ans_4_2D: 0},
	{test_4_2: 0},
	{ans_4_3A: 0},
	{ans_4_3B: 0},
	{ans_4_3C: 0},
	{ans_4_3D: 0},
	{test_4_3: 0},
	{ans_4_4A: 0},
	{ans_4_4B: 0},
	{ans_4_4C: 0},
	{ans_4_4D: 0},
	{test_4_4: 0},
	{ans_4_5A: 0},
	{ans_4_5B: 0},
	{ans_4_5C: 0},
	{ans_4_5D: 0},
	{test_4_5: 0},
	{test_4_6: 0},
	{ans_4_6A: 0},
	{ans_4_6B: 0},
	{ans_4_6C: 0},
	{ans_4_6D: 0},
	{test_4_7: 0},
	{ans_4_7A: 0},
	{ans_4_7B: 0},
	{ans_4_7C: 0},
	{ans_4_7D: 0},
	{ans_4_9A: 0},
	{ans_4_9B: 0},
	{ans_4_9C: 0},
	{ans_4_9D: 0},
	{test_4_9: 0},
	{ans_4_8A: 0},
	{ans_4_8B: 0},
	{ans_4_8C: 0},
	{ans_4_8D: 0},
	{test_4_8: 0},
	{ans_4_10A: 0},
	{ans_4_10B: 0},
	{ans_4_10C: 0},
	{ans_4_10D: 0},
	{test_4_10: 0},
	{memory: 0},
	{want: 0},
	{final_again: 0},
	{teach_4_1: 0},
	{"4endVideo": 0},
	{finalend: 0},
	{ch4_start: 0},
	{allend_bg: 0},
	{feedback: 0},
	{guji: 0},
	{furkids: 0},
	{again: 0},
	{one: 0},
	{back: 0},
	{next3: 0},
	{two: 0},
	{three: 0},
	{four: 0},
	{Mouse: 0},
	{Touch: 0},
	{lesson: 0},
	{logo: 0},
	{chapt1_map: 0},
	{音頻: 0},
	{talk_next: 0},
	{new_lesson: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{U: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Video: 0},
	{Sprite7: 0},
	{"3DCamera": 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{test_3_score: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{final_score: 0},
	{Browser: 0},
	{talk_front: 0},
	{map_intro2: 0},
	{open_diary2: 0},
	{open_diary3: 0},
	{open_diary4: 0},
	{END4: 0},
	{iknow_mini: 0},
	{iknow_small: 0},
	{iknow_middle: 0},
	{iknow_big: 0},
	{iknow_super: 0},
	{"1_1goto1": 0},
	{"1_1goto2": 0},
	{"1_1goto3": 0},
	{"1_1goto4": 0},
	{"1_1goto5": 0},
	{"1_1goto1_2": 0},
	{EAT_ONION: 0},
	{EAT_HAWAII: 0},
	{EAT_CHICKENBONE: 0},
	{EAT_AVOCADO: 0},
	{EATINTRO: 0},
	{EAT_CHOCOLATE: 0},
	{EAT_BLUEBERRY: 0},
	{EAT_PATIYA: 0},
	{EAT_WATERMELON: 0},
	{EAT_APPLE: 0},
	{EAT_GRAPE: 0},
	{EAT_ALLTASK: 0},
	{EAT_TASK2: 0},
	{EAT_TASK3: 0},
	{"1_3_teachno": 0},
	{"1_3_1": 0},
	{"1_3_2": 0},
	{"1_3_3": 0},
	{"1_3_4": 0},
	{"1_3_final_score": 0},
	{"1_2goto1_3": 0},
	{"2_1goto2_2": 0},
	{"2_2goto2_3": 0},
	{"2_3goto2_4": 0},
	{"2_3_1_grass": 0},
	{"2_3_1_noise": 0},
	{"2_3_1_hot": 0},
	{"2_3_teach": 0},
	{"2_3_ans": 0},
	{"2_3_2_ans_teach": 0},
	{"2_3_2_law": 0},
	{"2_2circle": 0},
	{"2_1_fnw": 0},
	{"2_1_ashbin": 0},
	{"2_1_house": 0},
	{"2_1_fence": 0},
	{"2_1_chest": 0},
	{"2_1_carpet": 0},
	{"2_1_air": 0},
	{"2_4_teachno": 0},
	{"2_4_1": 0},
	{"2_4_3": 0},
	{"2_4_4": 0},
	{"2_4_5": 0},
	{"2_4_final_score": 0},
	{"2_4_2": 0},
	{"3_2_gameS": 0},
	{"3_2_gameK": 0},
	{"3_2_teach": 0},
	{"3_2goto3_3": 0},
	{IsAiming: 0},
	{"3_1_1": 0},
	{"3_1_START1": 0},
	{"3_1_INTRO": 0},
	{IsAiming2: 0},
	{"3_1_22": 0},
	{"3_1_2": 0},
	{"3_1_START2": 0},
	{"3_1_31": 0},
	{"3_1_33": 0},
	{"3_1_START3": 0},
	{"3_1_32": 0},
	{"3_1goto3_2": 0},
	{"3_4_game_correct1": 0},
	{"3_4_game_correct2": 0},
	{"3_4_game_correct3": 0},
	{"3_4goto3_5": 0},
	{"3_5_final_score": 0},
	{"3_5_4": 0},
	{"3_5_5": 0},
	{"3_5_2": 0},
	{"3_5_3": 0},
	{"3_5_teachno": 0},
	{"3_5_1": 0},
	{"3_3bar": 0},
	{"3_3touch": 0},
	{"3_3goto3_4": 0},
	{"3_3_0": 0},
	{"4_1_teachno": 0},
	{"4_1_1": 0},
	{"4_1final": 0},
	{"4_1_2": 0},
	{"4_1_3": 0},
	{"4_1_4": 0},
	{"4_1_5": 0},
	{"4_1_6": 0},
	{"4_1_7": 0},
	{"4_1_8": 0},
	{"4_1_9": 0},
	{"4_1_10": 0}
];

self.InstanceType = {
	Diary1: class extends self.ISpriteInstance {},
	Diary2: class extends self.ISpriteInstance {},
	DiaryBG: class extends self.ISpriteInstance {},
	Diary3: class extends self.ISpriteInstance {},
	Diary4: class extends self.ISpriteInstance {},
	diary_intro: class extends self.ISpriteInstance {},
	Xdiary: class extends self.ISpriteInstance {},
	diary_lessonX: class extends self.ISpriteInstance {},
	finish: class extends self.ISpriteInstance {},
	finish2: class extends self.ISpriteInstance {},
	finish3: class extends self.ISpriteInstance {},
	finish4: class extends self.ISpriteInstance {},
	startb: class extends self.ISpriteInstance {},
	startbg: class extends self.ISpriteInstance {},
	Xstart: class extends self.ISpriteInstance {},
	start_intro: class extends self.ISpriteInstance {},
	SKIP: class extends self.ISpriteInstance {},
	_1_1talkBG: class extends self.ISpriteInstance {},
	_1_1talk1: class extends self.ISpriteInstance {},
	_1_1talk2: class extends self.ISpriteInstance {},
	X1_1: class extends self.ISpriteInstance {},
	talk: class extends self.ISpriteInstance {},
	talk2: class extends self.ISpriteInstance {},
	Chihuahua: class extends self.ISpriteInstance {},
	Chihuahua_information: class extends self.ISpriteInstance {},
	Pomeranian: class extends self.ISpriteInstance {},
	Pomeranian_information: class extends self.ISpriteInstance {},
	iknow_1_2_2: class extends self.ISpriteInstance {},
	Pug: class extends self.ISpriteInstance {},
	Pug_information: class extends self.ISpriteInstance {},
	dachshund: class extends self.ISpriteInstance {},
	dachshund_information: class extends self.ISpriteInstance {},
	iknow_1_2_3: class extends self.ISpriteInstance {},
	iknow_1_2_4: class extends self.ISpriteInstance {},
	corgi: class extends self.ISpriteInstance {},
	corgi_information: class extends self.ISpriteInstance {},
	borderCollie: class extends self.ISpriteInstance {},
	borderCollie_information: class extends self.ISpriteInstance {},
	iknow_1_2_5: class extends self.ISpriteInstance {},
	goldenRetriever: class extends self.ISpriteInstance {},
	goldenRetriever_information: class extends self.ISpriteInstance {},
	Labrador: class extends self.ISpriteInstance {},
	Labrador_information: class extends self.ISpriteInstance {},
	iknow_1_2_6: class extends self.ISpriteInstance {},
	molosser: class extends self.ISpriteInstance {},
	molosser_informationpng: class extends self.ISpriteInstance {},
	CaucasianSheepdog: class extends self.ISpriteInstance {},
	CaucasianSheepdog_informationpng: class extends self.ISpriteInstance {},
	_1_2_firstpage_bigSquare: class extends self.ISpriteInstance {},
	_1_2_firstpage_giantSquare: class extends self.ISpriteInstance {},
	_1_2_firstpage_mediumSquare: class extends self.ISpriteInstance {},
	_1_2_firstpage_miniSquare: class extends self.ISpriteInstance {},
	_1_2_firstpage_smallSquare: class extends self.ISpriteInstance {},
	_1_2_fistpageBackground: class extends self.ISpriteInstance {},
	first_teach: class extends self.ISpriteInstance {},
	_1_2lesson: class extends self.ISpriteInstance {},
	cross_teach: class extends self.ISpriteInstance {},
	cross_lesson: class extends self.ISpriteInstance {},
	cross_tip: class extends self.ISpriteInstance {},
	_1_1_X: class extends self.ISpriteInstance {},
	_1_1background: class extends self.ISpriteInstance {},
	_1_1bigSquare: class extends self.ISpriteInstance {},
	_1_1borderCollieSquare: class extends self.ISpriteInstance {},
	_1_1CaucasianShepherdDog: class extends self.ISpriteInstance {},
	_1_1ChihuahuaSquare: class extends self.ISpriteInstance {},
	_1_1corgiSquare: class extends self.ISpriteInstance {},
	_1_1dachshundSquare: class extends self.ISpriteInstance {},
	_1_1giantSquare: class extends self.ISpriteInstance {},
	_1_1goldenRetriever: class extends self.ISpriteInstance {},
	_1_1intro: class extends self.ISpriteInstance {},
	_1_1LabradorSquare: class extends self.ISpriteInstance {},
	_1_1mediumSquare: class extends self.ISpriteInstance {},
	_1_1miniSquare: class extends self.ISpriteInstance {},
	_1_1PomeranianSquare: class extends self.ISpriteInstance {},
	_1_1PugSquare: class extends self.ISpriteInstance {},
	_1_1smallSquare: class extends self.ISpriteInstance {},
	_1_1teach: class extends self.ISpriteInstance {},
	_1_1tibetanMastiff: class extends self.ISpriteInstance {},
	_1_2_2background: class extends self.ISpriteInstance {},
	_1_2_2intro: class extends self.ISpriteInstance {},
	_1_2_2teach: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	text_big: class extends self.ITextInstance {},
	text_big2: class extends self.ITextInstance {},
	text_medium: class extends self.ITextInstance {},
	text_mini: class extends self.ITextInstance {},
	text_small: class extends self.ITextInstance {},
	eatBG: class extends self.ISpriteInstance {},
	eat_hawaii_bean: class extends self.ISpriteInstance {},
	eat_chocolote: class extends self.ISpriteInstance {},
	eat_apple: class extends self.ISpriteInstance {},
	eat_pitaya: class extends self.ISpriteInstance {},
	eat_onion: class extends self.ISpriteInstance {},
	eat_grape: class extends self.ISpriteInstance {},
	eat_blueberry: class extends self.ISpriteInstance {},
	eat_watermelon: class extends self.ISpriteInstance {},
	eat_avocado: class extends self.ISpriteInstance {},
	eat_chicken_bone: class extends self.ISpriteInstance {},
	EAT_HAPPYDaiFront: class extends self.ISpriteInstance {},
	EAT_NO1: class extends self.ISpriteInstance {},
	EAT_NO3: class extends self.ISpriteInstance {},
	EAT_NO2: class extends self.ISpriteInstance {},
	EAT_TASK: class extends self.ISpriteInstance {},
	EATLIST2: class extends self.ISpriteInstance {},
	EATiknow: class extends self.ISpriteInstance {},
	EATintro: class extends self.ISpriteInstance {},
	talk3: class extends self.ISpriteInstance {},
	talk4: class extends self.ISpriteInstance {},
	map_station1_1: class extends self.ISpriteInstance {},
	map_station1_2: class extends self.ISpriteInstance {},
	map_station1_3: class extends self.ISpriteInstance {},
	map_station1_4: class extends self.ISpriteInstance {},
	map_station1_5: class extends self.ISpriteInstance {},
	map_station1_6: class extends self.ISpriteInstance {},
	map_1_1: class extends self.ISpriteInstance {},
	map_1_2: class extends self.ISpriteInstance {},
	map_1_3: class extends self.ISpriteInstance {},
	map_1_4: class extends self.ISpriteInstance {},
	map_1_5: class extends self.ISpriteInstance {},
	map_1_6: class extends self.ISpriteInstance {},
	Xmap2: class extends self.ISpriteInstance {},
	U1Grass: class extends self.ISpriteInstance {},
	map_intro: class extends self.ISpriteInstance {},
	openVideo: class extends self.IWorldInstance {},
	map_2_1: class extends self.ISpriteInstance {},
	map_2_2: class extends self.ISpriteInstance {},
	map_2_3: class extends self.ISpriteInstance {},
	map_2_4: class extends self.ISpriteInstance {},
	_3map: class extends self.ISpriteInstance {},
	map_3_1: class extends self.ISpriteInstance {},
	map_3_2: class extends self.ISpriteInstance {},
	map_3_3: class extends self.ISpriteInstance {},
	map_3_4: class extends self.ISpriteInstance {},
	map_3_5: class extends self.ISpriteInstance {},
	ch4_map: class extends self.ISpriteInstance {},
	map_: class extends self.ISpriteInstance {},
	list_logo: class extends self.ISpriteInstance {},
	list_intro: class extends self.ISpriteInstance {},
	list_light: class extends self.ISpriteInstance {},
	list_lesson: class extends self.ISpriteInstance {},
	list_map: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	test_1_: class extends self.ISpriteInstance {},
	_1_3_1A: class extends self.ISpriteInstance {},
	_1_3_1B: class extends self.ISpriteInstance {},
	_1_3_1C: class extends self.ISpriteInstance {},
	_1_3_1D: class extends self.ISpriteInstance {},
	test_1_2: class extends self.ISpriteInstance {},
	_1_3_2A: class extends self.ISpriteInstance {},
	_1_3_2B: class extends self.ISpriteInstance {},
	_1_3_2C: class extends self.ISpriteInstance {},
	_1_3_2D: class extends self.ISpriteInstance {},
	test_1_3: class extends self.ISpriteInstance {},
	_1_3_3A: class extends self.ISpriteInstance {},
	_1_3_3B: class extends self.ISpriteInstance {},
	test_1_4: class extends self.ISpriteInstance {},
	_1_3_4A: class extends self.ISpriteInstance {},
	_1_3_4B: class extends self.ISpriteInstance {},
	_1_3_4C: class extends self.ISpriteInstance {},
	_1_3_4D: class extends self.ISpriteInstance {},
	test_1_5: class extends self.ISpriteInstance {},
	test_1_final: class extends self.ISpriteInstance {},
	test_1_final_: class extends self.ISpriteInstance {},
	nextto2: class extends self.ISpriteInstance {},
	test_1_teach: class extends self.ISpriteInstance {},
	ans_1_1: class extends self.ISpriteInstance {},
	ans_1_2: class extends self.ISpriteInstance {},
	ans_1_3: class extends self.ISpriteInstance {},
	ans_1_4: class extends self.ISpriteInstance {},
	ans_1_5: class extends self.ISpriteInstance {},
	ans_1_1_chose: class extends self.ISpriteInstance {},
	ans_1_2_chose: class extends self.ISpriteInstance {},
	ans_1_3_chose: class extends self.ISpriteInstance {},
	ans_1_4_chose: class extends self.ISpriteInstance {},
	test_1_next: class extends self.ISpriteInstance {},
	test_1_final2: class extends self.ISpriteInstance {},
	next_to_1_2: class extends self.ISpriteInstance {},
	NEXTTOSPEAK: class extends self.ISpriteInstance {},
	DaiFront: class extends self.ISpriteInstance {},
	BG2: class extends self.ISpriteInstance {},
	next1_2_1: class extends self.ISpriteInstance {},
	next_level1_3: class extends self.ISpriteInstance {},
	next_level2_2: class extends self.ISpriteInstance {},
	BG2_2next: class extends self.ISpriteInstance {},
	BG1_1next: class extends self.ISpriteInstance {},
	next_level2_3: class extends self.ISpriteInstance {},
	next_level2_4: class extends self.ISpriteInstance {},
	_2_3_1_talk: class extends self.ISpriteInstance {},
	_2_3_1BG: class extends self.ISpriteInstance {},
	_2_3_1Grass: class extends self.ISpriteInstance {},
	_2_3_1Hot: class extends self.ISpriteInstance {},
	_2_3_1Noise: class extends self.ISpriteInstance {},
	_2_3_1Walk: class extends self.ISpriteInstance {},
	_2_3_1_teach: class extends self.ISpriteInstance {},
	_2_3_2BG: class extends self.ISpriteInstance {},
	_2_3_ans1: class extends self.ISpriteInstance {},
	_2_3_r: class extends self.ISpriteInstance {},
	_2_3_l: class extends self.ISpriteInstance {},
	_2_3_2_iknow: class extends self.ISpriteInstance {},
	_2_3_2_teach: class extends self.ISpriteInstance {},
	_2_3_2_hand: class extends self.ISpriteInstance {},
	_2_3_2cross: class extends self.ISpriteInstance {},
	_2_3_2_back: class extends self.ISpriteInstance {},
	_2_3_2_hand_infor: class extends self.ISpriteInstance {},
	_2_3_2_mask: class extends self.ISpriteInstance {},
	Walk_talk: class extends self.ISpriteInstance {},
	Law: class extends self.ISpriteInstance {},
	_2_3_2_next: class extends self.ISpriteInstance {},
	_2_3_2_Hand_move: class extends self.ISpriteInstance {},
	law_infor: class extends self.ISpriteInstance {},
	_2_2bg: class extends self.ISpriteInstance {},
	_2_2bag: class extends self.ISpriteInstance {},
	_2_2book: class extends self.ISpriteInstance {},
	_2_2anthelmintics: class extends self.ISpriteInstance {},
	_2_2doll: class extends self.ISpriteInstance {},
	_2_2cleaningSupplies: class extends self.ISpriteInstance {},
	_2_2scooper: class extends self.ISpriteInstance {},
	_2_2HarnessLesh: class extends self.ISpriteInstance {},
	_2_2tableware: class extends self.ISpriteInstance {},
	_2_2water: class extends self.ISpriteInstance {},
	_2_2lesson: class extends self.ISpriteInstance {},
	_2_2iknow: class extends self.ISpriteInstance {},
	_2_2c1: class extends self.ISpriteInstance {},
	_2_2c2: class extends self.ISpriteInstance {},
	_2_2c3: class extends self.ISpriteInstance {},
	_2_2c4: class extends self.ISpriteInstance {},
	_2_2c5: class extends self.ISpriteInstance {},
	_2_2X: class extends self.ISpriteInstance {},
	_2_2X2: class extends self.ISpriteInstance {},
	_2_2goal: class extends self.ISpriteInstance {},
	_2_2teach: class extends self.ISpriteInstance {},
	_2_2talk2: class extends self.ISpriteInstance {},
	_2_2talk1: class extends self.ISpriteInstance {},
	_22talk3png: class extends self.ISpriteInstance {},
	_2_2talkbg: class extends self.ISpriteInstance {},
	living: class extends self.ISpriteInstance {},
	airc: class extends self.ISpriteInstance {},
	ashbin: class extends self.ISpriteInstance {},
	fence: class extends self.ISpriteInstance {},
	fnw: class extends self.ISpriteInstance {},
	AIR: class extends self.ISpriteInstance {},
	carpet: class extends self.ISpriteInstance {},
	chest: class extends self.ISpriteInstance {},
	CHEST2: class extends self.ISpriteInstance {},
	FENCE2: class extends self.ISpriteInstance {},
	FOOD: class extends self.ISpriteInstance {},
	GROUND: class extends self.ISpriteInstance {},
	house: class extends self.ISpriteInstance {},
	HOUSE2: class extends self.ISpriteInstance {},
	TRASH: class extends self.ISpriteInstance {},
	Xa: class extends self.ISpriteInstance {},
	XCHEST: class extends self.ISpriteInstance {},
	Xg: class extends self.ISpriteInstance {},
	Xr: class extends self.ISpriteInstance {},
	Xfw: class extends self.ISpriteInstance {},
	Xh: class extends self.ISpriteInstance {},
	Xf: class extends self.ISpriteInstance {},
	no1: class extends self.ISpriteInstance {},
	no2: class extends self.ISpriteInstance {},
	_2_1intro: class extends self.ISpriteInstance {},
	robot2: class extends self.ISpriteInstance {},
	robottxt2: class extends self.ISpriteInstance {},
	robotend: class extends self.ISpriteInstance {},
	Xrobot: class extends self.ISpriteInstance {},
	_21ani: class extends self.IWorldInstance {},
	_21aniskip: class extends self.ISpriteInstance {},
	_2ov: class extends self.IWorldInstance {},
	_2_1OpenVidoe: class extends self.IWorldInstance {},
	LIST: class extends self.ISpriteInstance {},
	ROBOT: class extends self.ISpriteInstance {},
	ans_2_1A: class extends self.ISpriteInstance {},
	ans_2_1B: class extends self.ISpriteInstance {},
	test_2_1: class extends self.ISpriteInstance {},
	ans_2_1: class extends self.ISpriteInstance {},
	ans_2_1_chose: class extends self.ISpriteInstance {},
	ans_2_2A: class extends self.ISpriteInstance {},
	ans_2_2B: class extends self.ISpriteInstance {},
	ans_2_2C: class extends self.ISpriteInstance {},
	ans_2_2D: class extends self.ISpriteInstance {},
	test_2_2: class extends self.ISpriteInstance {},
	ans_2_2: class extends self.ISpriteInstance {},
	ans_2_2_chose: class extends self.ISpriteInstance {},
	ans_2_3A: class extends self.ISpriteInstance {},
	ans_2_3B: class extends self.ISpriteInstance {},
	ans_2_3C: class extends self.ISpriteInstance {},
	ans_2_3D: class extends self.ISpriteInstance {},
	test_2_3: class extends self.ISpriteInstance {},
	ans_2_3: class extends self.ISpriteInstance {},
	ans_2_3_chose: class extends self.ISpriteInstance {},
	test_2_4: class extends self.ISpriteInstance {},
	ans_2_4A: class extends self.ISpriteInstance {},
	ans_2_4C: class extends self.ISpriteInstance {},
	ans_2_4B: class extends self.ISpriteInstance {},
	ans_2_4D: class extends self.ISpriteInstance {},
	ans_2_4: class extends self.ISpriteInstance {},
	ans_2_4_chose: class extends self.ISpriteInstance {},
	ans_2_5A: class extends self.ISpriteInstance {},
	ans_2_5B: class extends self.ISpriteInstance {},
	test_2_5: class extends self.ISpriteInstance {},
	ans_2_5: class extends self.ISpriteInstance {},
	ans_2_5_chose: class extends self.ISpriteInstance {},
	test_2_teach: class extends self.ISpriteInstance {},
	test_2_next: class extends self.ISpriteInstance {},
	test_2_final: class extends self.ISpriteInstance {},
	test_2_score: class extends self.ISpriteInstance {},
	test_2_final_2: class extends self.ISpriteInstance {},
	nextto3: class extends self.ISpriteInstance {},
	test_3_final: class extends self.ISpriteInstance {},
	ch1next: class extends self.ISpriteInstance {},
	stomach_03: class extends self.ISpriteInstance {},
	knee_03: class extends self.ISpriteInstance {},
	knee_01: class extends self.ISpriteInstance {},
	stomach_02: class extends self.ISpriteInstance {},
	knee_02: class extends self.ISpriteInstance {},
	stomach_01: class extends self.ISpriteInstance {},
	_3_2_game_bg: class extends self.ISpriteInstance {},
	stomach_gif1: class extends self.ISpriteInstance {},
	knee_gif_1: class extends self.ISpriteInstance {},
	stomach_gif2: class extends self.ISpriteInstance {},
	stomach_gif3: class extends self.ISpriteInstance {},
	knee_gif_2: class extends self.ISpriteInstance {},
	knee_gif_3: class extends self.ISpriteInstance {},
	_3_2_game_squareS: class extends self.ISpriteInstance {},
	_3_2_game_squareK: class extends self.ISpriteInstance {},
	_3_2_game_teach: class extends self.ISpriteInstance {},
	_3_2_game_next: class extends self.ISpriteInstance {},
	_3_2_game_next_arrow: class extends self.ISpriteInstance {},
	_3_2bg: class extends self.ISpriteInstance {},
	Ok: class extends self.ISpriteInstance {},
	teach: class extends self.ISpriteInstance {},
	iframe: class extends self.IIframeInstance {},
	ipad: class extends self.ISpriteInstance {},
	Look_Continue: class extends self.ISpriteInstance {},
	Berner: class extends self.ISpriteInstance {},
	BernerPink: class extends self.ISpriteInstance {},
	CaucasianBlue: class extends self.ISpriteInstance {},
	CaucasianSheepdog2: class extends self.ISpriteInstance {},
	GreatDane: class extends self.ISpriteInstance {},
	GreatGreen: class extends self.ISpriteInstance {},
	molosser2: class extends self.ISpriteInstance {},
	molosserYellow: class extends self.ISpriteInstance {},
	Saint: class extends self.ISpriteInstance {},
	SaintOrange: class extends self.ISpriteInstance {},
	ShortPUR: class extends self.ISpriteInstance {},
	TaiwanMountain_: class extends self.ISpriteInstance {},
	TaiwanPurple: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	BGG: class extends self.ISpriteInstance {},
	C: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	DistanceRuler: class extends self.ITiledBackgroundInstance {},
	GRASS: class extends self.ISpriteInstance {},
	NEXT: class extends self.ISpriteInstance {},
	RestartButton: class extends self.IButtonInstance {},
	S: class extends self.ISpriteInstance {},
	S2: class extends self.ISpriteInstance {},
	SaintOrange2: class extends self.ISpriteInstance {},
	SaintOrange3: class extends self.ISpriteInstance {},
	SB: class extends self.ISpriteInstance {},
	SDOG: class extends self.ISpriteInstance {},
	Trail: class extends self.IParticlesInstance {},
	Bg3: class extends self.ISpriteInstance {},
	CatapultBlock: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	DOGS: class extends self.ISpriteInstance {},
	BD: class extends self.ISpriteInstance {},
	P1: class extends self.ISpriteInstance {},
	P2: class extends self.ISpriteInstance {},
	PBC: class extends self.ISpriteInstance {},
	PD: class extends self.ISpriteInstance {},
	PDOG3: class extends self.ISpriteInstance {},
	PPD: class extends self.ISpriteInstance {},
	PS1: class extends self.ISpriteInstance {},
	PS2: class extends self.ISpriteInstance {},
	Y1: class extends self.ISpriteInstance {},
	Y2: class extends self.ISpriteInstance {},
	YC: class extends self.ISpriteInstance {},
	YD: class extends self.ISpriteInstance {},
	YD2: class extends self.ISpriteInstance {},
	YDOG2: class extends self.ISpriteInstance {},
	YS1: class extends self.ISpriteInstance {},
	YS2: class extends self.ISpriteInstance {},
	YY: class extends self.ISpriteInstance {},
	END: class extends self.ISpriteInstance {},
	INTRO: class extends self.ISpriteInstance {},
	X: class extends self.ISpriteInstance {},
	doghand: class extends self.ISpriteInstance {},
	_3_4_game_bg: class extends self.ISpriteInstance {},
	circle_L1: class extends self.ISpriteInstance {},
	circle_L2: class extends self.ISpriteInstance {},
	circle_L3: class extends self.ISpriteInstance {},
	circle_R1: class extends self.ISpriteInstance {},
	circle_R2: class extends self.ISpriteInstance {},
	circle_R3: class extends self.ISpriteInstance {},
	_3_4_eggB: class extends self.ISpriteInstance {},
	_3_4_eggP: class extends self.ISpriteInstance {},
	_3_4_game_teach: class extends self.ISpriteInstance {},
	_3_4_Elf: class extends self.ISpriteInstance {},
	_3_4_photo: class extends self.ISpriteInstance {},
	_3_4_tip: class extends self.ISpriteInstance {},
	_3_4_light: class extends self.ISpriteInstance {},
	iframe2: class extends self.IIframeInstance {},
	_3_4ok: class extends self.ISpriteInstance {},
	_3_4teach: class extends self.ISpriteInstance {},
	_3ani: class extends self.IWorldInstance {},
	_3_3bg: class extends self.ISpriteInstance {},
	old_dai: class extends self.ISpriteInstance {},
	_3_3BAR: class extends self.ISpriteInstance {},
	_3_3hand: class extends self.ISpriteInstance {},
	_3_3brush: class extends self.ISpriteInstance {},
	_3_3eat: class extends self.ISpriteInstance {},
	_3_3health: class extends self.ISpriteInstance {},
	_3_3sport: class extends self.ISpriteInstance {},
	_3_3i: class extends self.ISpriteInstance {},
	_3_3clean: class extends self.ISpriteInstance {},
	_3_3_0mouth: class extends self.ISpriteInstance {},
	_3_3_0brain: class extends self.ISpriteInstance {},
	_3_3_0drain: class extends self.ISpriteInstance {},
	_3_3_0eyes: class extends self.ISpriteInstance {},
	_3_3_0hair: class extends self.ISpriteInstance {},
	cir_brain: class extends self.ISpriteInstance {},
	cir_drain: class extends self.ISpriteInstance {},
	cir_eyes: class extends self.ISpriteInstance {},
	cir_hair: class extends self.ISpriteInstance {},
	cir_hearing: class extends self.ISpriteInstance {},
	cir_mouth: class extends self.ISpriteInstance {},
	cir_power: class extends self.ISpriteInstance {},
	_3_3_0hearing: class extends self.ISpriteInstance {},
	_3_3_0power: class extends self.ISpriteInstance {},
	_3_30bar: class extends self.ISpriteInstance {},
	_3_3teach1: class extends self.ISpriteInstance {},
	NEXT2: class extends self.ISpriteInstance {},
	_3_3intro2: class extends self.ISpriteInstance {},
	_3_3END: class extends self.ISpriteInstance {},
	outtro: class extends self.ISpriteInstance {},
	_3_3teach2: class extends self.ISpriteInstance {},
	cursor2: class extends self.ISpriteInstance {},
	cursor3: class extends self.ISpriteInstance {},
	test_3_1: class extends self.ISpriteInstance {},
	ans_3_1A: class extends self.ISpriteInstance {},
	ans_3_1B: class extends self.ISpriteInstance {},
	ans_3_1C: class extends self.ISpriteInstance {},
	ans_3_1D: class extends self.ISpriteInstance {},
	ans_3_1: class extends self.ISpriteInstance {},
	ans_3_1_choose: class extends self.ISpriteInstance {},
	ans_3_2A: class extends self.ISpriteInstance {},
	ans_3_2B: class extends self.ISpriteInstance {},
	ans_3_2C: class extends self.ISpriteInstance {},
	ans_3_2D: class extends self.ISpriteInstance {},
	test_3_2: class extends self.ISpriteInstance {},
	ans_3_2: class extends self.ISpriteInstance {},
	ans_3_2_choose: class extends self.ISpriteInstance {},
	test_3_3: class extends self.ISpriteInstance {},
	ans_3_3: class extends self.ISpriteInstance {},
	ans_3_3_choose: class extends self.ISpriteInstance {},
	ans_3_3A: class extends self.ISpriteInstance {},
	ans_3_3C: class extends self.ISpriteInstance {},
	ans_3_3D: class extends self.ISpriteInstance {},
	ans_3_3B: class extends self.ISpriteInstance {},
	ans_3_4: class extends self.ISpriteInstance {},
	ans_3_4_choose: class extends self.ISpriteInstance {},
	ans_3_4A: class extends self.ISpriteInstance {},
	ans_3_4B: class extends self.ISpriteInstance {},
	ans_3_4C: class extends self.ISpriteInstance {},
	ans_3_4D: class extends self.ISpriteInstance {},
	test_3_4: class extends self.ISpriteInstance {},
	ans_3_5: class extends self.ISpriteInstance {},
	ans_3_5_choose: class extends self.ISpriteInstance {},
	ans_3_5A: class extends self.ISpriteInstance {},
	ans_3_5B: class extends self.ISpriteInstance {},
	test_3_5: class extends self.ISpriteInstance {},
	test_3_next: class extends self.ISpriteInstance {},
	ch3_s1_1: class extends self.ISpriteInstance {},
	ch3_s2: class extends self.ISpriteInstance {},
	ch3_s3_1: class extends self.ISpriteInstance {},
	ch3_s0_1: class extends self.ISpriteInstance {},
	ch3_s4_1: class extends self.ISpriteInstance {},
	go3_3: class extends self.ISpriteInstance {},
	ch3_end: class extends self.ISpriteInstance {},
	ready_go_4: class extends self.ISpriteInstance {},
	ch3_s0_2: class extends self.ISpriteInstance {},
	ch3_s0_3: class extends self.ISpriteInstance {},
	ch3_s1_2: class extends self.ISpriteInstance {},
	ch3_s1_3: class extends self.ISpriteInstance {},
	ch3_s1_4: class extends self.ISpriteInstance {},
	ch3_s3_2: class extends self.ISpriteInstance {},
	ch3_s3_3: class extends self.ISpriteInstance {},
	ch3_s3_4: class extends self.ISpriteInstance {},
	ch3_s3_7: class extends self.ISpriteInstance {},
	ch3_s3_5: class extends self.ISpriteInstance {},
	ch3_s3_6: class extends self.ISpriteInstance {},
	ch3_s4_2: class extends self.ISpriteInstance {},
	ch3_end2: class extends self.ISpriteInstance {},
	bg4: class extends self.ISpriteInstance {},
	_4_2_w4: class extends self.ISpriteInstance {},
	QR2: class extends self.ISpriteInstance {},
	_4_2w1: class extends self.ISpriteInstance {},
	_4_2w2: class extends self.ISpriteInstance {},
	k: class extends self.ISpriteInstance {},
	_4_2w3: class extends self.ISpriteInstance {},
	ans_4_1A: class extends self.ISpriteInstance {},
	ans_4_1B: class extends self.ISpriteInstance {},
	ans_4_1C: class extends self.ISpriteInstance {},
	ans_4_1D: class extends self.ISpriteInstance {},
	test_4_1: class extends self.ISpriteInstance {},
	ans_4_2A: class extends self.ISpriteInstance {},
	ans_4_2B: class extends self.ISpriteInstance {},
	ans_4_2C: class extends self.ISpriteInstance {},
	ans_4_2D: class extends self.ISpriteInstance {},
	test_4_2: class extends self.ISpriteInstance {},
	ans_4_3A: class extends self.ISpriteInstance {},
	ans_4_3B: class extends self.ISpriteInstance {},
	ans_4_3C: class extends self.ISpriteInstance {},
	ans_4_3D: class extends self.ISpriteInstance {},
	test_4_3: class extends self.ISpriteInstance {},
	ans_4_4A: class extends self.ISpriteInstance {},
	ans_4_4B: class extends self.ISpriteInstance {},
	ans_4_4C: class extends self.ISpriteInstance {},
	ans_4_4D: class extends self.ISpriteInstance {},
	test_4_4: class extends self.ISpriteInstance {},
	ans_4_5A: class extends self.ISpriteInstance {},
	ans_4_5B: class extends self.ISpriteInstance {},
	ans_4_5C: class extends self.ISpriteInstance {},
	ans_4_5D: class extends self.ISpriteInstance {},
	test_4_5: class extends self.ISpriteInstance {},
	test_4_6: class extends self.ISpriteInstance {},
	ans_4_6A: class extends self.ISpriteInstance {},
	ans_4_6B: class extends self.ISpriteInstance {},
	ans_4_6C: class extends self.ISpriteInstance {},
	ans_4_6D: class extends self.ISpriteInstance {},
	test_4_7: class extends self.ISpriteInstance {},
	ans_4_7A: class extends self.ISpriteInstance {},
	ans_4_7B: class extends self.ISpriteInstance {},
	ans_4_7C: class extends self.ISpriteInstance {},
	ans_4_7D: class extends self.ISpriteInstance {},
	ans_4_9A: class extends self.ISpriteInstance {},
	ans_4_9B: class extends self.ISpriteInstance {},
	ans_4_9C: class extends self.ISpriteInstance {},
	ans_4_9D: class extends self.ISpriteInstance {},
	test_4_9: class extends self.ISpriteInstance {},
	ans_4_8A: class extends self.ISpriteInstance {},
	ans_4_8B: class extends self.ISpriteInstance {},
	ans_4_8C: class extends self.ISpriteInstance {},
	ans_4_8D: class extends self.ISpriteInstance {},
	test_4_8: class extends self.ISpriteInstance {},
	ans_4_10A: class extends self.ISpriteInstance {},
	ans_4_10B: class extends self.ISpriteInstance {},
	ans_4_10C: class extends self.ISpriteInstance {},
	ans_4_10D: class extends self.ISpriteInstance {},
	test_4_10: class extends self.ISpriteInstance {},
	memory: class extends self.ISpriteInstance {},
	want: class extends self.ISpriteInstance {},
	final_again: class extends self.ISpriteInstance {},
	teach_4_1: class extends self.ISpriteInstance {},
	_4endVideo: class extends self.IWorldInstance {},
	finalend: class extends self.ISpriteInstance {},
	ch4_start: class extends self.ISpriteInstance {},
	allend_bg: class extends self.ISpriteInstance {},
	feedback: class extends self.ISpriteInstance {},
	guji: class extends self.ISpriteInstance {},
	furkids: class extends self.ISpriteInstance {},
	again: class extends self.ISpriteInstance {},
	one: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	next3: class extends self.ISpriteInstance {},
	two: class extends self.ISpriteInstance {},
	three: class extends self.ISpriteInstance {},
	four: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	lesson: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	chapt1_map: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	talk_next: class extends self.ISpriteInstance {},
	new_lesson: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	U: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	test_3_score: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	final_score: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	talk_front: class extends self.ISpriteInstance {}
}